remove some fo tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -88,20 +88,20 @@ jobs:
      # - name: Monitor RGB Test
        # run: |
          # timeout 60000 arduino-cli monitor -p /dev/ttyACM0 --fqbn esp32:esp32:esp32s3usbotg --config 115200 | tee rgb_test_output.log
-      - name: Upload Artefact
-        uses: actions/upload-artifact@v4
-        with:
-          name: rgb-test-log
-          path: rgb_test_output.log
+      #- name: Upload Artefact
+        #uses: actions/upload-artifact@v4
+       # with:
+        #  name: rgb-test-log
+        #  path: rgb_test_output.log
       # TODO Parse test result from log
-      - name: check test result
-        run: |
-          if grep -q "RGB LED Test: PASS" rgb_test_output.log; then
-            echo "RGB LED Test passed."
-          else
-            echo "RGB LED Test failed."
-            exit 1
-          fi
+      #- name: check test result
+       # run: |
+          #if grep -q "RGB LED Test: PASS" rgb_test_output.log; then
+         #   echo "RGB LED Test passed."
+        #  else
+         #   echo "RGB LED Test failed."
+        #    exit 1
+       #   fi
 
 
   sync:
